### PR TITLE
CI: Add Build Image workflow

### PR DESCRIPTION
**Pull request by andrewbird**
Remember it's a manual trigger on this one, we don't want it building upon every little push. Goto Actions/Build Image/Run Workflow.

### CODE REVIEW

**Comment by stsp** [comment]
So does this work?
If not - where is the log?

**Comment by andrewbird** [comment]
I added back in the fdpp dev requirements. Now the build runs to completion and deployment happened. See  https://github.com/andrewbird/fdpp-buildroot/actions and the deployment is here https://andrewbird.github.io/fdpp-buildroot/.

Should be good enough for you to merge and tweak now.

**Comment by stsp** [comment]
Thanks!
Could you please also provide
a PR against github pages
(branch pages) so that the build
to be here, not on your pages?

**Comment by stsp** [comment]
Buildroot uses ccache.
If we allow ccache to cache, then
we'll speed up the build time by the
factor of magnitude.
Do you know how to do that on
gh actions?

**Comment by andrewbird** [comment]
> Could you please also provide
a PR against github pages
(branch pages) so that the build
to be here, not on your pages?

There is no hardcoded destination, it should already deploy to this repo's pages branch. Please bear in mind that this action is manually triggered. see above

**Pull request merged**
